# config/meta.yml

meta_product_name: "Inpowaer"
meta_title: "Inpowaer -  L'application qui fait des jeunes des super heros de la communication"
meta_description: "Suivi personnel et quotidien pour les relations et la vie affective des jeunes et des adolescents"
meta_image: "facebook-card2.jpg"
